services:
  frontend:
    build:
      context: frontend/
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: true
    restart: always

  backend:
    build:
      context: backend/
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/probots
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: probots
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: probots@probots.net
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
