"""adding persistent player properties

Create Date: 2025-02-23 01:40:21.545616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d3427d14748'
down_revision: Union[str, None] = 'a365f409d59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color_head', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('color_tail', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('color_body', sa.String(length=20), nullable=True))
    op.drop_index('ix_users_session_id', table_name='users')
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.create_index('ix_users_session_id', 'users', ['session_id'], unique=True)
    op.drop_column('users', 'color_body')
    op.drop_column('users', 'color_tail')
    op.drop_column('users', 'color_head')
    # ### end Alembic commands ###
